In [1]:
import numpy as np

In [6]:
num_segments = 6
radius_m = 2

angles = np.linspace(0,2*np.pi,num_segments,endpoint=False)
print (angles)

[ 0.          1.04719755  2.0943951   3.14159265  4.1887902   5.23598776]


In [23]:
# calculate the loop coordinates
loop_coord_m = [np.array([radius_m*np.cos(angle), radius_m*np.sin(angle), 0]) for angle in angles]
print (loop_coord_m)

[array([ 2.,  0.,  0.]), array([ 1.        ,  1.73205081,  0.        ]), array([-1.        ,  1.73205081,  0.        ]), array([ -2.00000000e+00,   2.44929360e-16,   0.00000000e+00]), array([-1.        , -1.73205081,  0.        ]), array([ 1.        , -1.73205081,  0.        ])]


In [30]:
# make the \vec{dl} array
dl_m = []

for segment_idx in list(range(0,num_segments)):
    final_idx = segment_idx % num_segments
    ini_idx = (segment_idx + 1) % num_segments
    segment = loop_coord_m[final_idx] - loop_coord_m[ini_idx]
    dl_m.append(segment)
    
print(dl_m)

[ 1.         -1.73205081  0.        ]
[  2.00000000e+00  -2.22044605e-16   0.00000000e+00]
[ 1.          1.73205081  0.        ]
[-1.          1.73205081  0.        ]
[ -2.00000000e+00   1.11022302e-15   0.00000000e+00]
[-1.         -1.73205081  0.        ]
[array([ 1.        , -1.73205081,  0.        ]), array([  2.00000000e+00,  -2.22044605e-16,   0.00000000e+00]), array([ 1.        ,  1.73205081,  0.        ]), array([-1.        ,  1.73205081,  0.        ]), array([ -2.00000000e+00,   1.11022302e-15,   0.00000000e+00]), array([-1.        , -1.73205081,  0.        ])]


In [150]:
#location_m = np.array([-0.09, 0, -0.0173])
location_m = location_dict['J']

In [151]:
# first element in dl_m matches with second element in loop_coord_m
for idx in list(range(0,num_segments)):
    dl = dl_m[idx]
    r = location_m - loop_coord_m[(idx+1) % num_segments]
    print(idx)
    print("dl: " + repr(dl))
    print("r: " + repr(r) + repr(np.linalg.norm(r)))
    print("cross: " + repr(np.cross(dl,r)/np.linalg.norm(r)))
    print("dB: " + repr(np.cross(dl,r)/(np.linalg.norm(r)**3)))
    print("loc: " + repr(location_m))


0
dl: array([ 1.        , -1.73205081,  0.        ])
r: array([ -5.00000000e-01,  -1.73205081e+00,   6.12323400e-17])1.8027756377319946
cross: array([ -5.88301293e-17,  -3.39655910e-17,  -1.44115338e+00])
dB: array([ -1.81015782e-17,  -1.04509511e-17,  -4.43431811e-01])
loc: array([  5.00000000e-01,   0.00000000e+00,   6.12323400e-17])
1
dl: array([  2.00000000e+00,  -2.22044605e-16,   0.00000000e+00])
r: array([  1.50000000e+00,  -1.73205081e+00,   6.12323400e-17])2.2912878474779199
cross: array([ -5.93391649e-33,  -5.34479682e-17,  -1.51185789e+00])
dB: array([ -1.13026981e-33,  -1.01805654e-17,  -2.87972932e-01])
loc: array([  5.00000000e-01,   0.00000000e+00,   6.12323400e-17])
2
dl: array([ 1.        ,  1.73205081,  0.        ])
r: array([  2.50000000e+00,  -2.44929360e-16,   6.12323400e-17])2.5
cross: array([  4.24230095e-17,  -2.44929360e-17,  -1.73205081e+00])
dB: array([  6.78768153e-18,  -3.91886976e-18,  -2.77128129e-01])
loc: array([  5.00000000e-01,   0.00000000e+00,   6.1

In [53]:
label = 'A'

In [55]:
print (chr(ord(label)+0))

A


In [66]:
location_dict = dict()

label = 'A'
radius = 1/5
center = np.array([1,0,0])
for idx in list(range(0,num_segments)):
    angle = angles[idx]
    location = center + np.array([radius*np.cos(angle), 0, radius*np.sin(angle)])
    print (location)
    location_dict[chr(ord(label)+idx)] = location
    
label = 'G'
radius = 1/2
center = np.array([1,0,0])
for idx in list(range(0,num_segments)):
    angle = angles[idx]
    location = center + np.array([radius*np.cos(angle), 0, radius*np.sin(angle)])
    print (location)
    location_dict[chr(ord(label)+idx)] = location
    
label = 'A'
radius = 1/5
center = np.array([-1,0,0])
for idx in list(range(0,num_segments)):
    angle = angles[idx]
    location = center + np.array([radius*np.cos(angle), 0, radius*np.sin(angle)])
    print (location)
    key = chr(ord(label)+idx)
    location_dict[key*2] = location
    
label = 'G'
radius = 1/2
center = np.array([-1,0,0])
for idx in list(range(0,num_segments)):
    angle = angles[idx]
    location = center + np.array([radius*np.cos(angle), 0, radius*np.sin(angle)])
    print (location)
    key = chr(ord(label)+idx)
    location_dict[key*2] = location
    
print (location_dict)

[ 1.2  0.   0. ]
[ 1.1         0.          0.17320508]
[ 0.9         0.          0.17320508]
[  8.00000000e-01   0.00000000e+00   2.44929360e-17]
[ 0.9         0.         -0.17320508]
[ 1.1         0.         -0.17320508]
[ 1.5  0.   0. ]
[ 1.25       0.         0.4330127]
[ 0.75       0.         0.4330127]
[  5.00000000e-01   0.00000000e+00   6.12323400e-17]
[ 0.75       0.        -0.4330127]
[ 1.25       0.        -0.4330127]
[-0.8  0.   0. ]
[-0.9         0.          0.17320508]
[-1.1         0.          0.17320508]
[ -1.20000000e+00   0.00000000e+00   2.44929360e-17]
[-1.1         0.         -0.17320508]
[-0.9         0.         -0.17320508]
[-0.5  0.   0. ]
[-0.75       0.         0.4330127]
[-1.25       0.         0.4330127]
[ -1.50000000e+00   0.00000000e+00   6.12323400e-17]
[-1.25       0.        -0.4330127]
[-0.75       0.        -0.4330127]
{'KK': array([-1.25     ,  0.       , -0.4330127]), 'AA': array([-0.8,  0. ,  0. ]), 'I': array([ 0.75     ,  0.       ,  0.4330127]), '

In [64]:
'a'*2

'aa'

In [67]:
location_dict['AA']

array([-0.8,  0. ,  0. ])